---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - pip install netaddr
  - rm -rf molecule/resources/provisioning
  - ansible --version
  - ansible-lint --version
  - molecule --version
  - git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning

variables:
  GET_SOURCES_ATTEMPTS: "5"

Ansible lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - aws

Docker ggr:
  stage: deployment test
  script:
    - molecule test -s default
  tags:
    - aws

AWS ggr:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - apk add --no-cache unzip
    - molecule test -s cloud-aws-direct
  tags:
    - aws

EPC ggr:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-delegated
  tags:
    - delegated
