---
- name: Add universe repository for bionic
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present
  become: true

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present
    update_cache: true
  register: python3_install
  until: python3_install is succeeded
  become: true

- name: Install setuptools
  apt:
    name:
      - python3-setuptools
      - python-passlib
    update_cache: true
  register: installed_packages
  until: installed_packages is succeeded
  become: true
