---
# handlers file for ggr
- name: Reload systemd configuration
  systemd:
    daemon_reload: true
  become: true

- name: Restart selenoid-ui.service
  systemd:
    state: restarted
    name: selenoid-ui
  notify: Restart ggr.service
  become: true

- name: Restart ggr.service
  systemd:
    state: restarted
    name: ggr
  notify: Restart ggr-ui.service
  become: true

- name: Restart ggr-ui.service
  systemd:
    state: restarted
    name: ggr-ui
  become: true
